version: '3.7'

services:
  postgres:
    container_name: ${TYPEORM_HOST}
    image: postgres:12-alpine
    restart: always
    networks:
      - webnet
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
  main:
    container_name: api
    restart: unless-stopped
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
networks:
  webnet:
volumes:
  pgdata: