version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: ${ELASTIC_SEARCH_HOST}
    environment:
        - bootstrap.memory_lock=true
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
        memlock:
            soft: -1
            hard: -1
    volumes:
      - esdata01:/var/lib/elasticsearch/data
    ports:
      - ${ELASTIC_SEARCH_PORT}:${ELASTIC_SEARCH_PORT}
    networks:
      - webnet

  postgres:
    container_name: ${TYPEORM_HOST}
    image: postgres:12-alpine
    restart: always
    networks:
      - webnet
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  main:
    container_name: api
    restart: unless-stopped
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
      - elasticsearch

networks:
  webnet:
volumes:
  pgdata:
  esdata01: